{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-dash",
    "version": "2.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-dash-2.18.1.aar",
          "url": "exoplayer-dash-2.18.1.aar",
          "size": 130667,
          "sha512": "0eada0609a463c81dc343cc25ca6bc868833e3f2b3cceb41cdb463bfafb9e820d5054c3db49251bf97b6a721a855c453a05179cb3a74f66d56aab7c29e4e2291",
          "sha256": "ef8de823638ed80070059507353d5991d45a581efcb199e643728858a187d4e6",
          "sha1": "3ef2a8b0fd6f7b19b400d7eb27a2315de2d757c5",
          "md5": "6fffbb5b99a2f0db65674a420cad21a3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-dash-2.18.1.aar",
          "url": "exoplayer-dash-2.18.1.aar",
          "size": 130667,
          "sha512": "0eada0609a463c81dc343cc25ca6bc868833e3f2b3cceb41cdb463bfafb9e820d5054c3db49251bf97b6a721a855c453a05179cb3a74f66d56aab7c29e4e2291",
          "sha256": "ef8de823638ed80070059507353d5991d45a581efcb199e643728858a187d4e6",
          "sha1": "3ef2a8b0fd6f7b19b400d7eb27a2315de2d757c5",
          "md5": "6fffbb5b99a2f0db65674a420cad21a3"
        }
      ]
    }
  ]
}
