{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-extractor",
    "version": "2.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-extractor-2.18.1.aar",
          "url": "exoplayer-extractor-2.18.1.aar",
          "size": 710556,
          "sha512": "8a33b89180e9714cfe81484aea4883959476796e5412a65e3f6d692c4d4cd2d0cdfa25d19f11f426989fd8b63dde43c214d9d3eb1f970a53ff34210612956445",
          "sha256": "529a18b0a4130b87d96c50924ba8e3a725356574d1178b33d14479ada9ad006a",
          "sha1": "afd10333153de30e59ae2e64e5da74be5013c2e3",
          "md5": "2158b5059ec8522b89496daee067f08a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-common",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-decoder",
          "version": {
            "requires": "2.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-extractor-2.18.1.aar",
          "url": "exoplayer-extractor-2.18.1.aar",
          "size": 710556,
          "sha512": "8a33b89180e9714cfe81484aea4883959476796e5412a65e3f6d692c4d4cd2d0cdfa25d19f11f426989fd8b63dde43c214d9d3eb1f970a53ff34210612956445",
          "sha256": "529a18b0a4130b87d96c50924ba8e3a725356574d1178b33d14479ada9ad006a",
          "sha1": "afd10333153de30e59ae2e64e5da74be5013c2e3",
          "md5": "2158b5059ec8522b89496daee067f08a"
        }
      ]
    }
  ]
}
