{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-smoothstreaming",
    "version": "2.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-smoothstreaming-2.18.1.aar",
          "url": "exoplayer-smoothstreaming-2.18.1.aar",
          "size": 46677,
          "sha512": "d76fcef534a82f0e00ac1a525446a00569838522bbabe08b788312520dbe9d3c019574deb291f69722774556b424e997eb2af68ae724987eeaaa6c8f878e9d36",
          "sha256": "67204f34ac5ac474d6b87b97e057fa0189549db403dba99a57dfebdb2107c8c0",
          "sha1": "dfb3acc20cca1b954fd0e564ed9babbbcc84ab4f",
          "md5": "6cb490faf110c6a50b9e1fd8ab17cbe4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-smoothstreaming-2.18.1.aar",
          "url": "exoplayer-smoothstreaming-2.18.1.aar",
          "size": 46677,
          "sha512": "d76fcef534a82f0e00ac1a525446a00569838522bbabe08b788312520dbe9d3c019574deb291f69722774556b424e997eb2af68ae724987eeaaa6c8f878e9d36",
          "sha256": "67204f34ac5ac474d6b87b97e057fa0189549db403dba99a57dfebdb2107c8c0",
          "sha1": "dfb3acc20cca1b954fd0e564ed9babbbcc84ab4f",
          "md5": "6cb490faf110c6a50b9e1fd8ab17cbe4"
        }
      ]
    }
  ]
}
