{
  "formatVersion": "1.1",
  "component": {
    "group": "me.tatarka.bindingcollectionadapter2",
    "module": "bindingcollectionadapter",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gfzsk45pmffvfkj4titwv452k4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-core-ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "bindingcollectionadapter-4.0.0.aar",
          "url": "bindingcollectionadapter-4.0.0.aar",
          "size": 32418,
          "sha512": "11471fa6be33f028d43b10d2bd7d28ae753ebca1c0d71f2d29d80b8193b53a72ebef75ce177897d121e96b106d014eeee34b7a1ddc272707ceea0ea01e1f10f8",
          "sha256": "698683b02ef326ddceaf07e08303bd282ff317a1f44dc4ae4a08b13da4c6cf13",
          "sha1": "36d4aa1e9b4946a3c4ced4c757db6decf7d6977b",
          "md5": "017f74d71c5dc9bf84790e96dfb5d808"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "3.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "bindingcollectionadapter-4.0.0.aar",
          "url": "bindingcollectionadapter-4.0.0.aar",
          "size": 32418,
          "sha512": "11471fa6be33f028d43b10d2bd7d28ae753ebca1c0d71f2d29d80b8193b53a72ebef75ce177897d121e96b106d014eeee34b7a1ddc272707ceea0ea01e1f10f8",
          "sha256": "698683b02ef326ddceaf07e08303bd282ff317a1f44dc4ae4a08b13da4c6cf13",
          "sha1": "36d4aa1e9b4946a3c4ced4c757db6decf7d6977b",
          "md5": "017f74d71c5dc9bf84790e96dfb5d808"
        }
      ]
    }
  ]
}
