{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.exoplayer",
    "module": "exoplayer-hls",
    "version": "2.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "exoplayer-hls-2.18.1.aar",
          "url": "exoplayer-hls-2.18.1.aar",
          "size": 157887,
          "sha512": "9051164c2fea79f2bacc6c8389fa378bce0e7c0a321a57e19c49bde2aef4842605d6552e88dbf2e30dfc94e5c5668d4af6f61d1aa18bd482bafd699730938476",
          "sha256": "35f382e4f037fbd8805b9c084ae0c3485666ace265abd6490834a13a995430c7",
          "sha1": "293c989f6caea3789734742a6fefe2f3985c0d39",
          "md5": "30dd75ddf247ce20c5f4c8c3811507f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "exoplayer-hls-2.18.1.aar",
          "url": "exoplayer-hls-2.18.1.aar",
          "size": 157887,
          "sha512": "9051164c2fea79f2bacc6c8389fa378bce0e7c0a321a57e19c49bde2aef4842605d6552e88dbf2e30dfc94e5c5668d4af6f61d1aa18bd482bafd699730938476",
          "sha256": "35f382e4f037fbd8805b9c084ae0c3485666ace265abd6490834a13a995430c7",
          "sha1": "293c989f6caea3789734742a6fefe2f3985c0d39",
          "md5": "30dd75ddf247ce20c5f4c8c3811507f8"
        }
      ]
    }
  ]
}
